FROM kartoza/postgis:12.1
MAINTAINER tim@kartoza.com

RUN apt-get -y update; apt-get -y --no-install-recommends install postgresql-client cron
RUN touch /var/log/cron.log

ADD scripts /backup-scripts
RUN chmod 0755 /backup-scripts/*.sh

ENTRYPOINT ["/bin/bash", "/backup-scripts/start.sh"]
CMD ["/scripts/docker-entrypoint.sh"]

